--- 
platform: linux
image_resource:
  type: docker-image
  source: { repository: pallet/git-client }
run:
  path: bash
  args: [kong-resource-git/ci/tasks/notif/task.sh]
inputs:
- name: kong-resource-git
outputs:
- name: notification-content
